plugins {
    id 'com.android.application'
}

android {
    namespace 'ro.filarmonica.transilvania.stagiune'
    compileSdk 35

    defaultConfig {
        applicationId 'ro.filarmonica.transilvania.stagiune'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '0.2.0'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
